--
-------------------------------------------------------------------------------------------
-- Copyright © 2010-2011, Xilinx, Inc.
-- This file contains confidential and proprietary information of Xilinx, Inc. and is
-- protected under U.S. and international copyright and other intellectual property laws.
-------------------------------------------------------------------------------------------
--
-- Disclaimer:
-- This disclaimer is not a license and does not grant any rights to the materials
-- distributed herewith. Except as otherwise provided in a valid license issued to
-- you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
-- MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
-- DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
-- INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
-- OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
-- (whether in contract or tort, including negligence, or under any other theory
-- of liability) for any loss or damage of any kind or nature related to, arising
-- under or in connection with these materials, including for any direct, or any
-- indirect, special, incidental, or consequential loss or damage (including loss
-- of data, profits, goodwill, or any type of loss or damage suffered as a result
-- of any action brought by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-safe, or for use in any
-- application requiring fail-safe performance, such as life-support or safety
-- devices or systems, Class III medical devices, nuclear facilities, applications
-- related to the deployment of airbags, or any other applications that could lead
-- to death, personal injury, or severe property or environmental damage
-- (individually and collectively, "Critical Applications"). Customer assumes the
-- sole risk and liability of any use of Xilinx products in Critical Applications,
-- subject only to applicable laws and regulations governing limitations on product
-- liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
--
-------------------------------------------------------------------------------------------
--
--
-- Production definition of a 1K program for KCPSM6 in a Spartan-6 device using a 
-- RAMB18WER primitive.
--
-- Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
--       expansion with minimum changes being required to the hardware description. 
--       Only the lower 10-bits of the address are actually used for the 1K address range
--       000 to 3FF hex.  
--
-- Program defined by 'C:\FPGA\Contador_Cmod_S6_Fredyfrec\PSM\ROM.psm'.
--
-- Generated by KCPSM6 Assembler: 14 Oct 2018 - 14:30:33. 
--
-- Standard IEEE libraries
--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--
-- The Unisim Library is used to define Xilinx primitives. It is also used during
-- simulation. The source can be viewed at %XILINX%\vhdl\src\unisims\unisim_VCOMP.vhd
--  
library unisim;
use unisim.vcomponents.all;
--
--
entity ROM is
    Port (      address : in std_logic_vector(11 downto 0);
            instruction : out std_logic_vector(17 downto 0);
                 enable : in std_logic;
                    clk : in std_logic);
    end ROM;
--
architecture low_level_definition of ROM is
--
signal  address_a : std_logic_vector(13 downto 0);
signal  data_in_a : std_logic_vector(35 downto 0);
signal data_out_a : std_logic_vector(35 downto 0);
signal  address_b : std_logic_vector(13 downto 0);
signal  data_in_b : std_logic_vector(35 downto 0);
signal data_out_b : std_logic_vector(35 downto 0);
signal   enable_b : std_logic;
signal      clk_b : std_logic;
signal       we_b : std_logic_vector(3 downto 0);
--
begin
--
  address_a <= address(9 downto 0) & "0000";
  instruction <= data_out_a(33 downto 32) & data_out_a(15 downto 0);
  data_in_a <= "0000000000000000000000000000000000" & address(11 downto 10);
  --
  address_b <= "00000000000000";
  data_in_b <= "00" & data_out_b(33 downto 32) & "0000000000000000" & data_out_b(15 downto 0);
   enable_b <= '0';
       we_b <= "0000";
      clk_b <= '0';
  --
  --
  -- 
  kcpsm6_rom: RAMB16BWER
  generic map ( DATA_WIDTH_A => 18,
                DOA_REG => 0,
                EN_RSTRAM_A => FALSE,
                INIT_A => X"000000000",
                RST_PRIORITY_A => "CE",
                SRVAL_A => X"000000000",
                WRITE_MODE_A => "WRITE_FIRST",
                DATA_WIDTH_B => 18,
                DOB_REG => 0,
                EN_RSTRAM_B => FALSE,
                INIT_B => X"000000000",
                RST_PRIORITY_B => "CE",
                SRVAL_B => X"000000000",
                WRITE_MODE_B => "WRITE_FIRST",
                RSTTYPE => "SYNC",
                INIT_FILE => "NONE",
                SIM_COLLISION_CHECK => "ALL",
                SIM_DEVICE => "SPARTAN6",
                INIT_00 => X"B0050166004CD0021002F005F004D0401000D0031000E0029101E0101000113F",
                INIT_01 => X"2024D04CB0050166000E006C2000D0522100D04C20DED04B20AFD054207FD050",
                INIT_02 => X"D04C2007D04DB005016601000068003AA01CD002903F01002025006C2028D058",
                INIT_03 => X"500001791F025000D00210025000D0021001202B0100202B006C2000D0522035",
                INIT_04 => X"5000006CFF061F695000006CFF061F6B500001791F0A01791F0D500001791F03",
                INIT_05 => X"5000006CFF061F635000006CFF061F745000006CFF061F705000006CFF061F65",
                INIT_06 => X"00400179BF06003D5000006CFF061F665000006CFF061F775000006CFF061F73",
                INIT_07 => X"0054500000505000E075D002A07DD004207CD001903F50002071D001903F5000",
                INIT_08 => X"D009D00810FFD007B01DD006B01CD005B01BD004B01A020501CF0194F0041001",
                INIT_09 => X"00370093006C2000D05220A4D043207FD050209FD053B00501660060D0401000",
                INIT_0A => X"005820930040024901D9B51DB41CB31BB21A01791F50003D201C007500640071",
                INIT_0B => X"D0401000D007D006D005D00410FFD009B01BD008B01A020501CF0194F0041001",
                INIT_0C => X"00640071003700C1006C2000D05220D3D04320AFD05420CDD053B00501660060",
                INIT_0D => X"1003004820C10040024901D9B51DB41CB31BB21A01791F54003D5000201C0075",
                INIT_0E => X"D04320DED04B2007D04DB0050166005CD0401000D003B01A020501CF0194F004",
                INIT_0F => X"20E90040024901D9150014001300B21A01791F4B003D00E9006C2000D05220F5",
                INIT_10 => X"003D01D995079406930592040040024901791F50003D01D99503940293019200",
                INIT_11 => X"932592240040024901791F44003D01D995239422932192200040024901791F70",
                INIT_12 => X"01791F54003D01D9950F940E930D920C0040024901791F64003D01D995279426",
                INIT_13 => X"003D01D9951F941E931D921C0040023901D9950B940A9309920801791F2E0249",
                INIT_14 => X"120050000043006C0040023901D9951B941A9319921801791F2E024901791F74",
                INIT_15 => X"0000215F108011961298215F1040114B124C215F1040110D1203215F10101127",
                INIT_16 => X"10FF5000616FDF030173FF050173616FDF02017301945000615FB200B1009001",
                INIT_17 => X"BD045000DF802179217DD002904050009F8021736177D0109040500001AEF005",
                INIT_18 => X"01791F201E00218101791F2E6181DD026181DE231E011000DE280179AFE01E20",
                INIT_19 => X"90F6A19410C600F021A4DF0221A6DF03017361AED0089040218E1E011000DE20",
                INIT_1A => X"D010904021A790012194D0205000D130A1001028219401C82194FF2801B3A194",
                INIT_1B => X"A21091010100102821B410011000D128E200A21011010100102021AE9F801000",
                INIT_1C => X"102821CA11011000D128E010112010305000E200123021BD21C5D1209001E200",
                INIT_1D => X"61DB9E011F01E1F001E11F101E0A21D1110190011000D020E210320FA2001107",
                INIT_1E => X"AB708A60101D16001700180019A015001400130012000D500C400B300A205000",
                INIT_1F => X"47084808490E45004400430042062D902C802B700A6021FA4207A1F5AD90AC80",
                INIT_20 => X"1307180119001A001B00F01DF01CF01BF01A10001209500001A061EE90014608",
                INIT_21 => X"9101F01D20B0B01DF01C20A0B01CF01B2090B01BF01A0080B01A2221D100A130",
                INIT_22 => X"2A60295008404B004A00490048064B004A00490048060480059006A007B02211",
                INIT_23 => X"BF140246BF150246BF160246BF1750006210920113014B004A00490048062B70",
                INIT_24 => X"026D0269BF18026D0269BF191EFF500001791F3050000246BF120246BF130246",
                INIT_25 => X"BF12026D0269BF13026D0269BF14026D0269BF15026D0269BF16026D0269BF17",
                INIT_26 => X"1F302272DEFF50001E001000DF00500001791F30BF10026D0269BF11026D0269",
                INIT_27 => X"0000000000000000000000000000000000000000000000000000500050000179",
                INIT_28 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_29 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2A => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2B => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2C => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2D => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2E => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_2F => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_30 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_31 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_32 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_33 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_34 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_35 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_36 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_37 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_38 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_39 => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3A => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3B => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3C => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3D => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3E => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3F => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_00 => X"AACCC2C2A2A8A8A8A8A8A8A8A8A8A228A28A2AB774AAC2ADD2ADDDDD2A2A2360",
               INITP_01 => X"AA008AB7774A88AA2AA008AAAAB7774A8AA222A8AA8022AAAB7774A8A22222A8",
               INITP_02 => X"2AC22C2A2DAB6AD5202020202AA80228A00A80228A00A8A00A8A00A8A00A8A00",
               INITP_03 => X"5555567550000002D6825D802760A2D6109D842309DD0AAB74DDB09D828DD760",
               INITP_04 => X"0000002A7636928A28A28A28A2829A222222D5555555540264924934002A8235",
               INITP_05 => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_06 => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_07 => X"0000000000000000000000000000000000000000000000000000000000000000")
  port map(  ADDRA => address_a,
               ENA => enable,
              CLKA => clk,
               DOA => data_out_a(31 downto 0),
              DOPA => data_out_a(35 downto 32), 
               DIA => data_in_a(31 downto 0),
              DIPA => data_in_a(35 downto 32), 
               WEA => "0000",
            REGCEA => '0',
              RSTA => '0',
             ADDRB => address_b,
               ENB => enable_b,
              CLKB => clk_b,
               DOB => data_out_b(31 downto 0),
              DOPB => data_out_b(35 downto 32), 
               DIB => data_in_b(31 downto 0),
              DIPB => data_in_b(35 downto 32), 
               WEB => we_b,
            REGCEB => '0',
              RSTB => '0');
--
--
end low_level_definition;
--
------------------------------------------------------------------------------------
--
-- END OF FILE ROM.vhd
--
------------------------------------------------------------------------------------
